# ==============================================================================
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
# ==============================================================================

FROM ubuntu:20.04

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    libva-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]

# Use non-root user
ARG GROUP_ID=10000
ARG USER_ID=10001
RUN addgroup --gid ${GROUP_ID} --system appgroup \
 && adduser --uid ${USER_ID} --system --gid ${GROUP_ID} appuser
USER appuser

HEALTHCHECK CMD gcc --version || exit 1
