# ==============================================================================
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
# ==============================================================================

FROM ubuntu:20.04

ARG CLANG_VER=12

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    clang-${CLANG_VER} \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && clang-${CLANG_VER} -v \
 && apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3-pip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && pip3 install --no-cache-dir clang libclang

WORKDIR /data
VOLUME ["/data"]

# Use non-root user
ARG GROUP_ID=10000
ARG USER_ID=10001
RUN addgroup --gid ${GROUP_ID} --system appgroup \
 && adduser --uid ${USER_ID} --system --gid ${GROUP_ID} appuser
USER appuser

HEALTHCHECK CMD clang --version || exit 1
