# ==============================================================================
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
# ==============================================================================

ARG VPL_BUILD_DEPENDENCIES=/oneVPL/_deps
ARG VPL_INSTALL_PREFIX=/opt/intel/onevpl

# Stage 1
FROM ubuntu:20.04 AS vpl_base
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow
RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      git \
      pkg-config \
      yasm \
      nasm \
      cmake \
      python3 \
      python3-setuptools \
      python3-pip && \
    pip3 install -U wheel --user && \
    pip3 install meson ninja && \
    rm -rf /var/lib/apt/lsits/*


# Stage 2
FROM vpl_base AS vpl_bootstrap
COPY script /oneVPL/script
ARG VPL_BUILD_DEPENDENCIES
RUN /oneVPL/script/bootstrap


# Stage 3
FROM vpl_base AS vpl_build
COPY . /oneVPL
COPY --from=vpl_bootstrap /oneVPL/_deps /oneVPL/_deps
COPY --from=vpl_bootstrap /oneVPL/_extbuild /oneVPL/_extbuild
ARG VPL_BUILD_DEPENDENCIES
ARG VPL_INSTALL_PREFIX
RUN cd /oneVPL && \
    mkdir _build && \
    cd _build && \
    cmake -DCMAKE_INSTALL_PREFIX=${VPL_INSTALL_PREFIX} .. && \
    make -j $(nproc --all) && \
    make install


# Runtime image build
FROM ubuntu:20.04 
LABEL Description="This is the base image for the oneAPI Video Processing Library CPU Reference Implementation"
LABEL Vendor="Intel Corporation"
ARG VPL_INSTALL_PREFIX
ENV LD_LIBRARY_PATH=${VPL_INSTALL_PREFIX}/lib
ENV PKG_CONFIG_PATH=${VPL_INSTALL_PREFIX}/pkgconfig
ENV PATH="${PATH}:/${VPL_INSTALL_PREFIX}/bin"
COPY --from=vpl_build ${VPL_INSTALL_PREFIX} ${VPL_INSTALL_PREFIX} 
