# SPDX-FileCopyrightText: 2019-2020 Intel Corporation
#
# SPDX-License-Identifier: MIT

FROM ubuntu:20.04
COPY ubuntu-packages.txt install.sh requirements.txt /tmp/
WORKDIR /tmp
RUN ./install.sh

# Use non-root user
ARG GROUP_ID=10000
ARG USER_ID=10001
RUN addgroup --gid ${GROUP_ID} --system appgroup \
 && adduser --uid ${USER_ID} --system --gid ${GROUP_ID} appuser
USER appuser

HEALTHCHECK CMD python3 --version || exit 1
