#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
# Build project dependencies.

# Do not set Exit on Error in scripts that will be sourced
# set -o errexit

if [ -z "$BASH_VERSION" ]
then
  echo "This script must be run under bash"
  exit 1
fi

SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"

# Read command line options
. "${SCRIPT_DIR}/_buildopts.sh" \
    --name bootstrap \
    --desc "Build project dependencies." \
    -- "$@"

echo "Building project dependencies..."

pushd "${ROOT_DIR}"
    echo "Building base dependencies build folder..."
    . oneVPL/script/bootstrap ${FORWARD_OPTS}
    echo "Building cpu dependencies build folder..."
    . oneVPL-cpu/script/bootstrap ${FORWARD_OPTS}
popd
