#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
# Build base.

set -o errexit


SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"

# Read command line options
. "${SCRIPT_DIR}/_buildopts.sh" \
    --name build \
    --desc "Build base." \
    -- "$@"

if [ -n "${BOOTSTRAP_OPT}" ]
then
  echo "Building dependencies..."
  . "${SCRIPT_DIR}/bootstrap" ${FORWARD_OPTS}
fi

if [ -n "${VPL_INSTALL_DIR}" ]
then
  mkdir -p "${VPL_INSTALL_DIR}"
  INSTALL_PREFIX_CM_OPT="-DCMAKE_INSTALL_PREFIX=${VPL_INSTALL_DIR}"
fi

COFIG_CM_OPT="-DCMAKE_BUILD_TYPE=${COFIG_OPT}"

pushd "${PROJ_DIR}"
  BUILD_DIR=_build
  mkdir -p "${BUILD_DIR}"
  pushd "${BUILD_DIR}"
    cmake "${INSTALL_PREFIX_CM_OPT}" "${COFIG_CM_OPT}" -DBUILD_PYTHON_BINDING=1 "${PROJ_DIR}"
    make -j "$(nproc)" VERBOSE=1
    cmake --build . --config "${COFIG_OPT}" --target package
  popd
popd

# Signal to CI system 
if [ -n "${TEAMCITY_VERSION}" ]; then
  echo "##teamcity[publishArtifacts 'oneVPL/${BUILD_DIR}/*-all.zip=>']"
fi
