#!/bin/bash
###############################################################################
# Copyright (C) Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
## start of boilerplate to switch to project root ------------------------------
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
proj_dir="$( dirname "${script_dir}" )"
cd ${proj_dir}
set -o errexit

## Read options -----------------------------------------------------------
export BUILD_MODE= "Release"

while [ "$1" != "" ]; do
    case $1 in
        debug )
            export BUILD_MODE="Debug"
            ;;
        * )
            echo "usage: build [debug]"
            exit 1
    esac
    shift
done

## start of commands -----------------------------------------------------------
CMAKE_BINARY_DIR=_build

cmake --build ${CMAKE_BINARY_DIR} --config ${BUILD_MODE} --target install
