#!/bin/bash
###############################################################################
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
###############################################################################
## start of boilerplate to switch to project root ------------------------------
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
proj_dir="$( dirname "${script_dir}" )"
cd ${proj_dir}
set -o errexit
## start of commands -----------------------------------------------------------
CMAKE_BINARY_DIR=_build

mkdir -p ${CMAKE_BINARY_DIR}
cd ${CMAKE_BINARY_DIR}

cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --target package
