#!/bin/bash

export LD_LIBRARY_PATH=$PWD
let result_all=0

echo --- Running Decode Smoke Test ---
./sample_decode h265 -i ../test/content/cars_128x96.h265 -o out_vpl_h265.i420 -vpl 
$VPL_BUILD_DEPENDENCIES/bin/ffmpeg -y -i ../test/content/cars_128x96.h265 -f rawvideo -pix_fmt yuv420p out_ref_h265.i420
$VPL_BUILD_DEPENDENCIES/bin/ffmpeg -y -r 30 -s 128x96 -pix_fmt yuv420p -f rawvideo -i out_vpl_h265.i420 -r 30 -s 128x96 -pix_fmt yuv420p -f rawvideo -i out_ref_h265.i420 -filter_complex psnr= -f null nullsink
python3 $PYTHONPATH/check_content/check_smoke_output.py out_ref_h265.i420 out_vpl_h265.i420 I420 128x96@30

ret=$?
if [ $ret -ne 0 ]; then
    echo --- Decode Smoke Test FAILED ---
    let result_all++
else 
    echo --- Decode Smoke Test PASSED ---
fi

echo --- Running Encode Smoke Test ---
./sample_encode h265 -i out_ref_h265.i420 -o out_vpl.h265 -w 128 -h 96 -vpl 
./sample_decode h265 -i out_vpl.h265 -o out_vpl_dec_h265.i420 -vpl
$VPL_BUILD_DEPENDENCIES/bin/ffmpeg -y -r 30 -s 128x96 -pix_fmt yuv420p -f rawvideo -i out_ref_h265.i420 -r 30 -s 128x96 -pix_fmt yuv420p -f rawvideo -i out_vpl_dec_h265.i420 -filter_complex psnr= -f null nullsink
python3 $PYTHONPATH/check_content/check_smoke_output.py out_ref_h265.i420 out_vpl_dec_h265.i420 I420 128x96@30

ret=$?
if [ $ret -ne 0 ]; then
    echo --- Encode Smoke Test FAILED ---
    let result_all++
else 
    echo --- Encode Smoke Test PASSED ---
fi

exit $result_all

